# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 05:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('description', models.TextField(blank=True, max_length=512, verbose_name='queue description')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
