# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='finish',
            field=models.DateTimeField(blank=True, null=True, verbose_name='finish date'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start date'),
        ),
    ]
